"""Typst Vector PDF Document Generator & Compiler."""

from __future__ import annotations
import os
import io
import shutil
import tempfile
import subprocess
from typing import Dict, Any, Optional

from core.models.base import BaseContract
from core.models.supply import SupplyContract
from core.models.services import ServiceContract
from core.models.work import WorkContract
from core.templates.registry import ContractRegistry
from core.num_to_words import format_rubles


class TypstEngine:
    """Deterministic Typst vector document and PDF compilation engine."""

    @classmethod
    def generate_typst_markup(cls, contract: BaseContract) -> str:
        """Generate clean, publication-ready Typst code from contract object."""
        doc_structure = ContractRegistry.assemble_document_structure(contract)
        header = doc_structure["header"]
        metadata = doc_structure["metadata"]
        signatures = doc_structure["signatures"]

        lines = []

        # Typst page and font setup
        lines.append("// Auto-generated by DocGen Omnichannel Deterministic Core")
        lines.append('#set page(')
        lines.append('  paper: "a4",')
        lines.append('  margin: (left: 25mm, right: 15mm, top: 20mm, bottom: 20mm),')
        lines.append('  header: align(right, text(size: 8pt, fill: luma(120))[')
        lines.append(f'    {header["title"]} // {header["date"]}')
        lines.append('  ]),')
        lines.append('  footer: [')
        lines.append('    #set text(size: 9pt, fill: luma(100))')
        lines.append('    #grid(')
        lines.append('      columns: (1fr, 1fr),')
        lines.append('      align(left)[Экземпляр Сторон],')
        lines.append('      align(right)[Стр. #context counter(page).display() из #context counter(page).final().first()]')
        lines.append('    )')
        lines.append('  ]')
        lines.append(')')
        lines.append('')
        lines.append('#set text(font: ("Liberation Serif", "Times New Roman", "DejaVu Serif"), size: 11pt, lang: "ru")')
        lines.append('#set par(justify: true, first-line-indent: 1.25cm, leading: 0.65em)')
        lines.append('#set heading(numbering: none)')
        lines.append('')

        # Document Title
        lines.append(f'#align(center)[#text(size: 13pt, weight: "bold")[{header["title"]}]]')
        lines.append('#v(2pt)')

        # City and Date
        lines.append('#grid(')
        lines.append('  columns: (1fr, 1fr),')
        lines.append(f'  align(left)[{header["city"]}],')
        lines.append(f'  align(right)[«{header["date"]}»]')
        lines.append(')')
        lines.append('#v(6pt)')

        # Preamble
        escaped_preamble = header["text"].replace('"', '\\"')
        lines.append(f'{escaped_preamble}')
        lines.append('')

        # Sections
        for section in doc_structure["sections"]:
            lines.append('#v(8pt)')
            lines.append(f'#align(center)[#text(size: 11.5pt, weight: "bold")[{section["section_num"]}. {section["title"]}]]')
            lines.append('#v(4pt)')

            for clause in section["clauses"]:
                escaped_text = clause["text"].replace('"', '\\"')
                lines.append(f'* {clause["num"]}. * {escaped_text}')
                lines.append('')

            # Custom specification table for Supply
            if section["section_num"] == "1" and isinstance(contract, SupplyContract) and contract.items:
                lines.append('#v(6pt)')
                lines.append('#align(center)[#table(')
                lines.append('  columns: (30pt, 1fr, 50pt, 50pt, 75pt, 75pt),')
                lines.append('  align: (center, left, center, right, right, right),')
                lines.append('  fill: (col, row) => if row == 0 { rgb("F2F2F2") } else { none },')
                lines.append('  [*№*], [*Наименование*], [*Ед.*], [*Кол-во*], [*Цена (руб.)*], [*Сумма (руб.)*],')

                for idx, item in enumerate(contract.items, start=1):
                    item_name_esc = item.name.replace('"', '\\"')
                    lines.append(
                        f'  [{idx}], [{item_name_esc}], [{item.unit}], [{item.quantity:g}], '
                        f'[{format_rubles(item.price_per_unit)}], [{format_rubles(item.total_price)}],'
                    )

                lines.append(f'  table.cell(colspan: 5, align: right)[*ИТОГО:*], [{format_rubles(contract.total_amount)}]')
                lines.append(')]')
                lines.append('#v(6pt)')

            # Custom stages table for Work
            if section["section_num"] == "1" and isinstance(contract, WorkContract) and contract.stages:
                lines.append('#v(6pt)')
                lines.append('#align(center)[#table(')
                lines.append('  columns: (35pt, 1.2fr, 90pt, 80pt),')
                lines.append('  align: (center, left, center, right),')
                lines.append('  fill: (col, row) => if row == 0 { rgb("F2F2F2") } else { none },')
                lines.append('  [*Этап*], [*Наименование работ*], [*Сроки*], [*Стоимость (руб.)*],')

                for stage in contract.stages:
                    stage_title_esc = stage.title.replace('"', '\\"')
                    lines.append(
                        f'  [№ {stage.stage_number}], [{stage_title_esc}], '
                        f'[{stage.start_date} -- {stage.end_date}], [{format_rubles(stage.cost)}],'
                    )

                lines.append(f'  table.cell(colspan: 3, align: right)[*ИТОГО:*], [{format_rubles(contract.total_amount)}]')
                lines.append(')]')
                lines.append('#v(6pt)')

        # Signatures
        lines.append('#v(12pt)')
        lines.append('#align(center)[#text(size: 11.5pt, weight: "bold")[РЕКВИЗИТЫ И ПОДПИСИ СТОРОН]]')
        lines.append('#v(6pt)')

        client_lines = [f'*{signatures["client"]["role_title"]}*', f'*{signatures["client"]["party_name"]}*']
        client_lines.extend(signatures["client"]["details_lines"][1:])
        client_content = "\\\n".join(client_lines) + f"\\\n\\\n{signatures['client']['signatory_position']}:\\\n_________________ / {signatures['client']['signatory_name']} /\\\n*М.П.*"

        vendor_lines = [f'*{signatures["vendor"]["role_title"]}*', f'*{signatures["vendor"]["party_name"]}*']
        vendor_lines.extend(signatures["vendor"]["details_lines"][1:])
        vendor_content = "\\\n".join(vendor_lines) + f"\\\n\\\n{signatures['vendor']['signatory_position']}:\\\n_________________ / {signatures['vendor']['signatory_name']} /\\\n*М.П.*"

        lines.append('#grid(')
        lines.append('  columns: (1fr, 1fr),')
        lines.append('  gutter: 20pt,')
        lines.append('  [')
        lines.append(f'    {client_content}')
        lines.append('  ],')
        lines.append('  [')
        lines.append(f'    {vendor_content}')
        lines.append('  ]')
        lines.append(')')

        return "\n".join(lines)

    @classmethod
    def compile_pdf(cls, contract: BaseContract) -> bytes:
        """Compile contract to PDF using Typst CLI or return raw typst markup if binary not on PATH."""
        markup = cls.generate_typst_markup(contract)

        typst_bin = shutil.which("typst")
        if typst_bin:
            with tempfile.TemporaryDirectory() as tmpdir:
                typ_file = os.path.join(tmpdir, "document.typ")
                pdf_file = os.path.join(tmpdir, "document.pdf")
                with open(typ_file, "w", encoding="utf-8") as f:
                    f.write(markup)

                proc = subprocess.run(
                    [typst_bin, "compile", typ_file, pdf_file],
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    timeout=15,
                )
                if proc.returncode == 0 and os.path.exists(pdf_file):
                    with open(pdf_file, "rb") as f:
                        return f.read()

        # Fallback: return UTF-8 encoded typst markup if typst compiler is unavailable
        return markup.encode("utf-8")
